global.levelguardabot = ""
mode = 0
done = 0
s = 2
global.DSM_level = 0
global.debug1 = 0
global.debug2 = 0
global.debug3 = 0
global.debug4 = 0
global.name_user = ""
global.name_users = ""
global.last_level = ""
global.condiciones = 0
global.condiciones_clear = 0
global.condiciones_type = 0
global.condiciones_object = 0
global.condiciones_count = 0
cronometro = 0
cronometro_play = 0
cronometro_restart = 0
minutos = 0
segundos = 0
pasos = 0
cronometro_cp_minutos = 0
cronometro_cp_segundos = 0
cronometro_cp_pasos = 0
global.minutos_r = 0
global.segundos_r = 0
global.pasos_r = 0
vk_movimientos = 0
vk_saltos = 0
pad_x = 44
pad_y = 155
pad_startx = 44
pad_starty = 155
pad_active = 0
pad_movex = 0
pad_movey = 0
modo_android = 0
global.fireworks = 1
global.save_changes = 0
global.controles_tactiles = 1
global.sm4j_style = 0
alpha_sm4j = 0.7
global.snds_editor = 1
global.effect_star = 1
global.idioma = 0
global.sonidos = 1
global.modo_noche = 0
global.entorno = "ground"
global.shadows_obj = 0.25
global.apariencia = 2
opacidad = 0.5
global.key_br = 0
back = -1
message = ""
showfps = 0
scr_init_globals()
global.gw = 384
global.gh = 216
port_x = 0
port_y = 0
global.carrieditem = -4
global.carriedsprite = -4
global.shallihold = 0
global.levelmusic = 210
global.acecoins = ds_map_create()
global.worldmap = ds_map_create()
global.cardgame = ds_map_create()
global.messagefont = font_add_sprite_ext(spr_messagefont, "ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789.", 0, 0)
global.font = font_add_sprite_ext(spr_spritefont, "abcdefghijklmnñopqrstuvwxyzABCDEFGHIJKLMNÑOPQRSTUVWXYZ0123456789,_[]()-.", 0, 0)
global.font_white = font_add_sprite_ext(spr_spritefont_white, "abcdefghijklmnñopqrstuvwxyzABCDEFGHIJKLMNÑOPQRSTUVWXYZ0123456789,_[]()-.", 0, 0)
global.font_password = font_add_sprite_ext(spr_spritefont_password, "abcdefghijklmnñopqrstuvwxyzABCDEFGHIJKLMNÑOPQRSTUVWXYZ0123456789,_[]()-.", 0, 0)
global.wdigits_SMB = font_add_sprite_ext(spr_SMB_numbers, "0123456789", 0, 0)
global.wdigits_SMB3 = font_add_sprite_ext(spr_SMB3_numbers, "0123456789", 0, 0)
global.wdigits = font_add_sprite_ext(spr_numbers, "0123456789", 0, 0)
global.wdigits_NSMBU = font_add_sprite_ext(spr_NSMBU_numbers, "0123456789", 0, 0)
global.wdigits_NSMBU_coins = font_add_sprite_ext(spr_NSMBU_numbers_coins, "0123456789", 0, 0)
global.wdigits_SMB2 = font_add_sprite_ext(spr_SMB2_numbers, "0123456789", 0, 0)
global.big_digits = font_add_sprite_ext(spr_numbers_big, "0123456789", 0, 0)
global.time_digits = font_add_sprite_ext(spr_numbers_time, "0123456789", 0, 0)
global.time_digits_white = font_add_sprite_ext(spr_numbers_time_white, "0123456789", 0, 0)
global.numbers_lives = font_add_sprite_ext(spr_numbers_lives, "0123456789", 0, 0)
global.numbers_start = font_add_sprite_ext(spr_numbers_mario_start, "1234567890/", 0, 0)
global.numbers_datetime = font_add_sprite_ext(spr_font_datetime, "0123456789/:", 0, 0)
global.numbers_points = font_add_sprite_ext(spr_font_puntaje, "0123456789:", 0, 0)
global.gdigits = font_add_sprite_ext(spr_numbersgold, "0123456789", 0, 0)
directorio_temp = ""
global.directorio_temp = (working_directory + "/Niveles/")
global.directorio = (working_directory + "/Niveles/")
global.directorio_temporal = (working_directory + "/temp/")
keyboard_set_map(ord("X"), vk_shift)
keyboard_set_map(ord("Z"), vk_control)
gamepad = gamepad_is_connected(0)
leftstick[0] = 0
leftstick[1] = 0
leftstick[2] = 0
leftstick[3] = 0
math_set_epsilon(0.00001)
application_surface_draw_enable(0)

