// Initialise the global array that allows the lookup of the depth of a given object
// GM2.0 does not have a depth on objects so on import from 1.x a global array is created
// NOTE: MacroExpansion is used to insert the array initialisation at import time
gml_pragma( "global", "__global_object_depths()");

// insert the generated arrays here
global.__objectDepths[0] = -9; // obj_lighting
global.__objectDepths[1] = 12; // obj_flagpole
global.__objectDepths[2] = 11; // obj_SMB_flag
global.__objectDepths[3] = -6; // obj_score_flag
global.__objectDepths[4] = 10; // obj_SMB_castle
global.__objectDepths[5] = 10; // obj_SMB_castle_front
global.__objectDepths[6] = 11; // obj_mini_flag
global.__objectDepths[7] = 301; // obj_goalcard
global.__objectDepths[8] = -5; // obj_goalcard_get
global.__objectDepths[9] = 9; // obj_goalgate
global.__objectDepths[10] = -11; // obj_goalgate_front
global.__objectDepths[11] = 8; // obj_goalgate_tape
global.__objectDepths[12] = 0; // obj_crystalorb
global.__objectDepths[13] = 0; // obj_hawmask
global.__objectDepths[14] = -8; // obj_mario
global.__objectDepths[15] = -8; // obj_marioU
global.__objectDepths[16] = 8; // obj_checkpoint
global.__objectDepths[17] = -11; // obj_levelmanager
global.__objectDepths[18] = 0; // obj_autoscroll
global.__objectDepths[19] = 0; // obj_bganimator
global.__objectDepths[20] = -5; // obj_warpmario
global.__objectDepths[21] = -14; // obj_shake_mario
global.__objectDepths[22] = 0; // obj_platform_help
global.__objectDepths[23] = 0; // obj_stormmaker
global.__objectDepths[24] = 0; // obj_fallow_view
global.__objectDepths[25] = 0; // obj_galoomba
global.__objectDepths[26] = 0; // obj_galoomba2
global.__objectDepths[27] = 0; // obj_shoegoomba
global.__objectDepths[28] = -7; // obj_koopa
global.__objectDepths[29] = -7; // obj_koopa_red
global.__objectDepths[30] = 0; // obj_beachkoopa
global.__objectDepths[31] = 0; // obj_beachkoopa_red
global.__objectDepths[32] = -2; // obj_floruga
global.__objectDepths[33] = 0; // obj_floruga_body
global.__objectDepths[34] = 0; // obj_buzzybeetle
global.__objectDepths[35] = 0; // obj_spiny
global.__objectDepths[36] = 0; // obj_buzzy_ceiling
global.__objectDepths[37] = -6; // obj_jumppiranha
global.__objectDepths[38] = 0; // obj_plant_fire
global.__objectDepths[39] = -2; // obj_spiketop
global.__objectDepths[40] = -7; // obj_cheepcheep
global.__objectDepths[41] = -7; // obj_cheepcheep2
global.__objectDepths[42] = -7; // obj_blooper
global.__objectDepths[43] = -7; // obj_angrysun
global.__objectDepths[44] = -7; // obj_happymoon
global.__objectDepths[45] = -2; // obj_monty_chase
global.__objectDepths[46] = -2; // obj_spike
global.__objectDepths[47] = -3; // obj_spike_ball
global.__objectDepths[48] = 0; // obj_snow_ball
global.__objectDepths[49] = -1; // obj_snow_ball_held
global.__objectDepths[50] = -2; // obj_pokey
global.__objectDepths[51] = -2; // obj_boo
global.__objectDepths[52] = -2; // obj_mechakoopa_held
global.__objectDepths[53] = -5; // obj_mechakoopa_debris
global.__objectDepths[54] = -2; // obj_blastakoopa_bullet
global.__objectDepths[55] = -2; // obj_zappakoopa_beam
global.__objectDepths[56] = -3; // obj_zappakoopa_beameff
global.__objectDepths[57] = -2; // obj_zappakoopa_laser
global.__objectDepths[58] = -1; // obj_mechakoopa
global.__objectDepths[59] = -1; // obj_blastakoopa
global.__objectDepths[60] = -1; // obj_zappakoopa
global.__objectDepths[61] = 0; // obj_drybones
global.__objectDepths[62] = -2; // obj_thwomp
global.__objectDepths[63] = -2; // obj_thwomp_2
global.__objectDepths[64] = -7; // obj_podoboo
global.__objectDepths[65] = -7; // obj_grinder
global.__objectDepths[66] = -2; // obj_magikoopa
global.__objectDepths[67] = 0; // obj_bobomb
global.__objectDepths[68] = 0; // obj_bobomb_big
global.__objectDepths[69] = 0; // obj_bobomb_ready
global.__objectDepths[70] = -2; // obj_bullebill_base
global.__objectDepths[71] = -2; // obj_bullebill_base_red
global.__objectDepths[72] = 10; // obj_bulletbill
global.__objectDepths[73] = 10; // obj_bulletbull_red
global.__objectDepths[74] = -3; // obj_banzaibill
global.__objectDepths[75] = 0; // obj_rockywrench
global.__objectDepths[76] = -3; // obj_cannon
global.__objectDepths[77] = -3; // obj_cannon_red
global.__objectDepths[78] = -2; // obj_soplete
global.__objectDepths[79] = -2; // obj_soplete_alt
global.__objectDepths[80] = -7; // obj_chain_chomp_free
global.__objectDepths[81] = -1; // obj_SMB_bowser
global.__objectDepths[82] = -2; // obj_bowser
global.__objectDepths[83] = -2; // obj_boomboom
global.__objectDepths[84] = -2; // obj_hammerbro
global.__objectDepths[85] = -2; // obj_sledgebro
global.__objectDepths[86] = -2; // obj_charginchuck
global.__objectDepths[87] = -7; // obj_wings_dead
global.__objectDepths[88] = -7; // obj_paracaidas_dead
global.__objectDepths[89] = 5; // obj_paracaidas_go
global.__objectDepths[90] = 1; // obj_solid
global.__objectDepths[91] = 1; // obj_solidtop
global.__objectDepths[92] = 1; // obj_climb
global.__objectDepths[93] = 1; // obj_climb_net
global.__objectDepths[94] = 1; // obj_swim
global.__objectDepths[95] = 1; // obj_slippery
global.__objectDepths[96] = -1; // obj_hurtsolid
global.__objectDepths[97] = -1; // obj_hurtsolid2
global.__objectDepths[98] = 0; // obj_slope_r
global.__objectDepths[99] = 0; // obj_slope_l
global.__objectDepths[100] = 0; // obj_slope_sr
global.__objectDepths[101] = 0; // obj_slope_sl
global.__objectDepths[102] = 0; // obj_islope_r
global.__objectDepths[103] = 0; // obj_islope_l
global.__objectDepths[104] = 0; // obj_islope_sr
global.__objectDepths[105] = 0; // obj_islope_sl
global.__objectDepths[106] = 0; // obj_fillwater
global.__objectDepths[107] = 0; // obj_stopblock
global.__objectDepths[108] = 9; // obj_block
global.__objectDepths[109] = 9; // obj_block_multicoin
global.__objectDepths[110] = 1; // obj_block_coinchain
global.__objectDepths[111] = 9; // obj_block_hidden
global.__objectDepths[112] = 9; // obj_flipblock
global.__objectDepths[113] = -7; // obj_noteblock
global.__objectDepths[114] = -7; // obj_musicblock
global.__objectDepths[115] = 1; // obj_onoffblock
global.__objectDepths[116] = 6; // obj_onoffplatform
global.__objectDepths[117] = 6; // obj_onoffplatform_blue
global.__objectDepths[118] = 9; // obj_block_rock
global.__objectDepths[119] = 9; // obj_block_ice
global.__objectDepths[120] = 1; // obj_pblock
global.__objectDepths[121] = 1; // obj_anti_pblock
global.__objectDepths[122] = 2; // obj_nube
global.__objectDepths[123] = 6; // obj_vine_green
global.__objectDepths[124] = 259; // obj_beanstalk
global.__objectDepths[125] = 260; // obj_vine
global.__objectDepths[126] = -1; // obj_muncher
global.__objectDepths[127] = -1; // obj_muncher_big
global.__objectDepths[128] = -2; // obj_pinchos
global.__objectDepths[129] = 1; // obj_berry
global.__objectDepths[130] = -5; // obj_estalactita
global.__objectDepths[131] = -5; // obj_estalactita2
global.__objectDepths[132] = 10; // obj_arrow
global.__objectDepths[133] = 0; // obj_cinta_parent
global.__objectDepths[134] = 0; // obj_cinta
global.__objectDepths[135] = 0; // obj_cinta_switch
global.__objectDepths[136] = -7; // obj_plataforma
global.__objectDepths[137] = -7; // obj_plataforma_blue
global.__objectDepths[138] = -7; // obj_donut
global.__objectDepths[139] = 5; // obj_fast_lava_lift
global.__objectDepths[140] = 5; // obj_lava_lift
global.__objectDepths[141] = 5; // obj_lava_lift_part
global.__objectDepths[142] = 1; // obj_coin
global.__objectDepths[143] = 9; // obj_icecoin
global.__objectDepths[144] = 1; // obj_pink_coin
global.__objectDepths[145] = 1; // obj_coin10
global.__objectDepths[146] = 1; // obj_coin30
global.__objectDepths[147] = 1; // obj_coin50
global.__objectDepths[148] = 0; // obj_spring
global.__objectDepths[149] = 0; // obj_spring_land
global.__objectDepths[150] = 1; // obj_coin_pow
global.__objectDepths[151] = 1; // obj_coin_pow_big
global.__objectDepths[152] = -2; // obj_pswitch
global.__objectDepths[153] = 0; // obj_pswitch_press
global.__objectDepths[154] = 0; // obj_block_pow_hold
global.__objectDepths[155] = -6; // obj_quicksand
global.__objectDepths[156] = -7; // obj_bumper
global.__objectDepths[157] = 6; // obj_onewaygate_right
global.__objectDepths[158] = 6; // obj_onewaygate_left
global.__objectDepths[159] = 6; // obj_onewaygate_top
global.__objectDepths[160] = 6; // obj_onewaygate_bottom
global.__objectDepths[161] = 0; // obj_key
global.__objectDepths[162] = 0; // obj_key_appear
global.__objectDepths[163] = -7; // obj_key_fallow
global.__objectDepths[164] = -3; // obj_torbellino
global.__objectDepths[165] = -7; // obj_bortice
global.__objectDepths[166] = 11; // obj_tuberia
global.__objectDepths[167] = 5; // obj_door
global.__objectDepths[168] = 5; // obj_door_exit
global.__objectDepths[169] = 5; // obj_door_switch
global.__objectDepths[170] = 5; // obj_door_switch_exit
global.__objectDepths[171] = 5; // obj_door_lock
global.__objectDepths[172] = 5; // obj_door_lock_exit
global.__objectDepths[173] = 0; // obj_deactivation
global.__objectDepths[174] = 0; // obj_physicsparent
global.__objectDepths[175] = 0; // obj_powerupparent
global.__objectDepths[176] = 0; // obj_enemyparent
global.__objectDepths[177] = 0; // obj_deactenemyparent
global.__objectDepths[178] = -2; // obj_bossparent
global.__objectDepths[179] = -1; // obj_blockparent
global.__objectDepths[180] = 0; // obj_worldparent
global.__objectDepths[181] = 0; // obj_panelparent
global.__objectDepths[182] = 0; // obj_holdparent
global.__objectDepths[183] = -11; // obj_parcarry
global.__objectDepths[184] = 0; // obj_slopeparent
global.__objectDepths[185] = -2; // obj_enemyparent_held
global.__objectDepths[186] = 0; // obj_enemyparent_lava
global.__objectDepths[187] = -14; // obj_deadmario
global.__objectDepths[188] = -5; // obj_doormario
global.__objectDepths[189] = -8; // obj_puller
global.__objectDepths[190] = -5; // obj_player_goal_smb1
global.__objectDepths[191] = -5; // obj_player_goal_smb3
global.__objectDepths[192] = -5; // obj_player_goal_smw
global.__objectDepths[193] = -5; // obj_player_goal_smw_castle
global.__objectDepths[194] = -5; // obj_player_goal_smb2
global.__objectDepths[195] = 0; // obj_slider
global.__objectDepths[196] = -8; // obj_spinner
global.__objectDepths[197] = -6; // obj_mario_transform2
global.__objectDepths[198] = -2; // obj_1up
global.__objectDepths[199] = -2; // obj_mushroom
global.__objectDepths[200] = -2; // obj_fireflower
global.__objectDepths[201] = -2; // obj_turnip
global.__objectDepths[202] = 2; // obj_superflower
global.__objectDepths[203] = -7; // obj_cap
global.__objectDepths[204] = -2; // obj_megamushroom
global.__objectDepths[205] = -2; // obj_hen_mushroom
global.__objectDepths[206] = -2; // obj_star
global.__objectDepths[207] = 2; // obj_frogsuit
global.__objectDepths[208] = 2; // obj_iceflower
global.__objectDepths[209] = 2; // obj_blueshell
global.__objectDepths[210] = 2; // obj_penguinsuit
global.__objectDepths[211] = 2; // obj_propellershroom
global.__objectDepths[212] = 2; // obj_boomerangflower
global.__objectDepths[213] = 2; // obj_acorn
global.__objectDepths[214] = -2; // obj_egg
global.__objectDepths[215] = 2; // obj_egg_hatch
global.__objectDepths[216] = -7; // obj_yoshi2
global.__objectDepths[217] = -4; // obj_yoshi_runaway
global.__objectDepths[218] = -7; // obj_yoshi_abandon
global.__objectDepths[219] = -7; // obj_yoshifire
global.__objectDepths[220] = 0; // obj_yoshifire_purple
global.__objectDepths[221] = -7; // obj_yoshifire_one
global.__objectDepths[222] = -7; // obj_tongue
global.__objectDepths[223] = -2; // obj_egg_red
global.__objectDepths[224] = -7; // obj_yoshi_red
global.__objectDepths[225] = 0; // obj_getshoe
global.__objectDepths[226] = -9; // obj_kuriboshoe
global.__objectDepths[227] = -9; // obj_kuriboshoe2
global.__objectDepths[228] = -7; // obj_smoke_shoe
global.__objectDepths[229] = 0; // obj_kuriboshoe_movement
global.__objectDepths[230] = -9; // obj_kuribo_drybones
global.__objectDepths[231] = -9; // obj_helmet
global.__objectDepths[232] = -9; // obj_helmet_spiny
global.__objectDepths[233] = 2; // obj_clown
global.__objectDepths[234] = 2; // obj_clown_fire
global.__objectDepths[235] = -12; // obj_fire_clown
global.__objectDepths[236] = -12; // obj_fire_clown_small
global.__objectDepths[237] = -12; // obj_clown_smoke
global.__objectDepths[238] = -7; // obj_clown_explotion
global.__objectDepths[239] = -4; // obj_cap_mario
global.__objectDepths[240] = 10; // obj_powerupsprout
global.__objectDepths[241] = -2; // obj_fireball
global.__objectDepths[242] = -2; // obj_superball
global.__objectDepths[243] = -1; // obj_superball_trail
global.__objectDepths[244] = -9; // obj_invincibility
global.__objectDepths[245] = -7; // obj_brohammer_yoshi
global.__objectDepths[246] = -7; // obj_bones_yoshi
global.__objectDepths[247] = -7; // obj_bones_yoshi_one
global.__objectDepths[248] = 0; // obj_galoomba_hold
global.__objectDepths[249] = 0; // obj_galoomba_hold2
global.__objectDepths[250] = -7; // obj_plantfire
global.__objectDepths[251] = 0; // obj_espina
global.__objectDepths[252] = 0; // obj_angrysun_movement
global.__objectDepths[253] = 0; // obj_crumblebones
global.__objectDepths[254] = -7; // obj_magic
global.__objectDepths[255] = -7; // obj_bone
global.__objectDepths[256] = 0; // obj_bobomb_hold
global.__objectDepths[257] = -2; // obj_cannonball
global.__objectDepths[258] = 0; // obj_cannonball_red
global.__objectDepths[259] = -2; // obj_wrench
global.__objectDepths[260] = -7; // obj_bowser_fire
global.__objectDepths[261] = -7; // obj_bowserfire_up
global.__objectDepths[262] = -7; // obj_bowser_fire_down
global.__objectDepths[263] = -8; // obj_enemy_dead
global.__objectDepths[264] = -8; // obj_enemy_dead_castle
global.__objectDepths[265] = 0; // obj_enemy_multidead
global.__objectDepths[266] = 0; // obj_stomped
global.__objectDepths[267] = -1; // obj_shell
global.__objectDepths[268] = -1; // obj_shell_held
global.__objectDepths[269] = -1; // obj_shell_kamikaze
global.__objectDepths[270] = -1; // obj_shell_empty
global.__objectDepths[271] = -1; // obj_spiny_empty
global.__objectDepths[272] = -1; // obj_shell_drybones
global.__objectDepths[273] = -1; // obj_shell_drybones_held
global.__objectDepths[274] = -7; // obj_brohammer
global.__objectDepths[275] = 2; // obj_blockcoin
global.__objectDepths[276] = 2; // obj_coinchain
global.__objectDepths[277] = -7; // obj_shard
global.__objectDepths[278] = -1; // obj_veggiecoin
global.__objectDepths[279] = -1; // obj_multiveggiecoin
global.__objectDepths[280] = 0; // obj_coinchange
global.__objectDepths[281] = 0; // obj_blownbubble
global.__objectDepths[282] = 0; // obj_veggies_pull
global.__objectDepths[283] = -30; // obj_curtainin
global.__objectDepths[284] = -30; // obj_curtainout
global.__objectDepths[285] = -99; // obj_fadein
global.__objectDepths[286] = -99; // obj_fadeout
global.__objectDepths[287] = -2; // obj_score
global.__objectDepths[288] = -2; // obj_smoke
global.__objectDepths[289] = -6; // obj_statuesmoke
global.__objectDepths[290] = -7; // obj_spinsmoke
global.__objectDepths[291] = -9; // obj_spinthump
global.__objectDepths[292] = -1; // obj_bubble
global.__objectDepths[293] = -1; // obj_sparkletrail
global.__objectDepths[294] = 0; // obj_sparkles_coin
global.__objectDepths[295] = -12; // obj_scoregoal
global.__objectDepths[296] = -7; // obj_smoke_cap
global.__objectDepths[297] = -7; // obj_detroy_enemy
global.__objectDepths[298] = -8; // obj_rotten_signal
global.__objectDepths[299] = 0; // obj_gotas
global.__objectDepths[300] = -16; // obj_menu_pausa
global.__objectDepths[301] = -17; // obj_pausa_button
global.__objectDepths[302] = -17; // obj_button_sonidos_pausa
global.__objectDepths[303] = 10; // obj_axe_smw
global.__objectDepths[304] = 0; // obj_castle_floor
global.__objectDepths[305] = 10; // obj_castle
global.__objectDepths[306] = 10; // obj_castle_front
global.__objectDepths[307] = -7; // obj_explosion
global.__objectDepths[308] = 0; // obj_blockbumper
global.__objectDepths[309] = 0; // obj_stomp
global.__objectDepths[310] = -18; // obj_settings_panel
global.__objectDepths[311] = -19; // obj_configurar_controles
global.__objectDepths[312] = -19; // obj_button_settings_estrella
global.__objectDepths[313] = -19; // obj_button_settings_idioma
global.__objectDepths[314] = -19; // obj_button_settings_sm4j
global.__objectDepths[315] = -19; // obj_button_settings_sonidos
global.__objectDepths[316] = -19; // obj_selecting_player
global.__objectDepths[317] = -19; // obj_window_select
global.__objectDepths[318] = -19; // obj_button_settings_close
global.__objectDepths[319] = -10000; // obj_key_br
global.__objectDepths[320] = 0; // obj_inhibidor_vk
global.__objectDepths[321] = -10; // obj_sidefade
global.__objectDepths[322] = 0; // obj_intro_control
global.__objectDepths[323] = -26; // obj_title_controller
global.__objectDepths[324] = -25; // obj_title_oprime
global.__objectDepths[325] = -25; // obj_editor_screen
global.__objectDepths[326] = -25; // obj_play_screen
global.__objectDepths[327] = 0; // obj_load_level
global.__objectDepths[328] = -99; // obj_persistent
global.__objectDepths[329] = -100; // obj_mariostart
global.__objectDepths[330] = -101; // obj_mariostart_mario
global.__objectDepths[331] = 10; // obj_arrow_big
global.__objectDepths[332] = -22; // object556
global.__objectDepths[333] = 0; // obj_cursor_mask
global.__objectDepths[334] = -10000; // obj_d_pad
global.__objectDepths[335] = 100; // obj_DSM_control
global.__objectDepths[336] = 0; // obj_DSM_level
global.__objectDepths[337] = 0; // obj_DSM_mario
global.__objectDepths[338] = -5; // obj_DSM_button
global.__objectDepths[339] = 0; // obj_castle_start
global.__objectDepths[340] = 0; // obj_guardabot
global.__objectDepths[341] = 0; // obj_load_guardabot
global.__objectDepths[342] = -5; // obj_gb_button
global.__objectDepths[343] = 0; // obj_bt_gb_next
global.__objectDepths[344] = 0; // obj_bt_gb_before
global.__objectDepths[345] = -6; // obj_gb_level
global.__objectDepths[346] = -7; // obj_bt_gb_play
global.__objectDepths[347] = -7; // obj_bt_gb_delete
global.__objectDepths[348] = -7; // obj_bt_gb_close
global.__objectDepths[349] = 0; // obj_input_name_user
global.__objectDepths[350] = 0; // obj_input_password
global.__objectDepths[351] = 0; // obj_button_name_user
global.__objectDepths[352] = 0; // obj_button_save_id
global.__objectDepths[353] = -20; // obj_superado_bg
global.__objectDepths[354] = -21; // obj_button_superado
global.__objectDepths[355] = -5; // obj_game_over
global.__objectDepths[356] = -100; // obj_time_up
global.__objectDepths[357] = 0; // obj_button_start
global.__objectDepths[358] = 0; // obj_button_back
global.__objectDepths[359] = 0; // obj_button_niveles_mundiales
global.__objectDepths[360] = 0; // obj_SMB1_walk
global.__objectDepths[361] = 0; // obj_desafio_munchers
global.__objectDepths[362] = -5; // obj_mario_victory
global.__objectDepths[363] = -5; // obj_princess
global.__objectDepths[364] = -11; // obj_apariencia
global.__objectDepths[365] = -12; // obj_card_logo
global.__objectDepths[366] = -11; // obj_bg_selection
global.__objectDepths[367] = -12; // obj_bg1
global.__objectDepths[368] = -11; // obj_time
global.__objectDepths[369] = -12; // obj_button_ok
global.__objectDepths[370] = -12; // obj_button_time
global.__objectDepths[371] = -11; // obj_autoavance
global.__objectDepths[372] = -12; // obj_button_autoavance
global.__objectDepths[373] = -11; // obj_condiciones
global.__objectDepths[374] = -12; // obj_condiciones_button
global.__objectDepths[375] = -12; // obj_tabs_condiciones
global.__objectDepths[376] = -25; // obj_alert_condicion
global.__objectDepths[377] = -11; // obj_card_expand
global.__objectDepths[378] = 0; // obj_button_home
global.__objectDepths[379] = -15; // obj_edit_menu
global.__objectDepths[380] = -16; // obj_button_paloma
global.__objectDepths[381] = -16; // obj_settings_button
global.__objectDepths[382] = -16; // obj_button_close_menu
global.__objectDepths[383] = 10; // obj_ground2
global.__objectDepths[384] = 300; // obj_ground3
global.__objectDepths[385] = -11; // obj_panel_save_load
global.__objectDepths[386] = -12; // obj_button_save_load
global.__objectDepths[387] = -12; // obj_button_save_changes
global.__objectDepths[388] = -15; // obj_panel_list
global.__objectDepths[389] = -16; // obj_list_item
global.__objectDepths[390] = -15; // obj_alert_load
global.__objectDepths[391] = -16; // obj_noti_load_button
global.__objectDepths[392] = -16; // obj_bt_load_next
global.__objectDepths[393] = -16; // obj_bt_load_before
global.__objectDepths[394] = -18; // obj_load_image
global.__objectDepths[395] = -15; // obj_window_alert
global.__objectDepths[396] = -16; // obj_button_notification_aceptar
global.__objectDepths[397] = -16; // obj_button_notification_cancelar
global.__objectDepths[398] = -16; // obj_input
global.__objectDepths[399] = -18; // obj_toast
global.__objectDepths[400] = -16; // obj_etiquetas
global.__objectDepths[401] = 9; // obj_ground_title
global.__objectDepths[402] = -14; // obj_creator_jugar_editar
global.__objectDepths[403] = -10; // obj_menu_editor
global.__objectDepths[404] = -10; // obj_menu_editor_ext
global.__objectDepths[405] = -12; // obj_robot
global.__objectDepths[406] = -10; // obj_erase
global.__objectDepths[407] = -10; // obj_card_block_sounds
global.__objectDepths[408] = -12; // obj_logo_game
global.__objectDepths[409] = -12; // obj_card_bg
global.__objectDepths[410] = -12; // obj_card_bout
global.__objectDepths[411] = -12; // obj_card_autoavance
global.__objectDepths[412] = -12; // obj_panel_time
global.__objectDepths[413] = -12; // obj_card_condiciones
global.__objectDepths[414] = -10; // obj_card_rocket
global.__objectDepths[415] = -10; // obj_expand
global.__objectDepths[416] = -10; // obj_dog
global.__objectDepths[417] = -10; // obj_card_item
global.__objectDepths[418] = -9; // obj_lave_draw
global.__objectDepths[419] = -8; // obj_panel_left
global.__objectDepths[420] = -12; // obj_night_change
global.__objectDepths[421] = -10; // obj_expand_panels
global.__objectDepths[422] = -10; // obj_expand_panels_left
global.__objectDepths[423] = -10; // obj_expand_paneles_top
global.__objectDepths[424] = -19; // obj_rocket_anim
global.__objectDepths[425] = 280; // obj_decoracion_1
global.__objectDepths[426] = 280; // obj_decoracion_2
global.__objectDepths[427] = 280; // obj_decoracion_3
global.__objectDepths[428] = 280; // obj_decoracion_4
global.__objectDepths[429] = 0; // obj_decoracion_parent
global.__objectDepths[430] = 280; // obj_modelbgo
global.__objectDepths[431] = 5; // obj_modelsolid
global.__objectDepths[432] = 270; // obj_modelsizable
global.__objectDepths[433] = 1; // obj_ground
global.__objectDepths[434] = 0; // obj_tile_trigger
global.__objectDepths[435] = 0; // obj_pswitch_res
global.__objectDepths[436] = 0; // obj_pow_res
global.__objectDepths[437] = 0; // obj_rock_res
global.__objectDepths[438] = 0; // obj_ice_res
global.__objectDepths[439] = 0; // obj_coin_res
global.__objectDepths[440] = 0; // obj_icecoin_res
global.__objectDepths[441] = 0; // obj_pink_coin_res
global.__objectDepths[442] = 0; // obj_coin10_res
global.__objectDepths[443] = 0; // obj_coin30_res
global.__objectDepths[444] = 0; // obj_coin50_res
global.__objectDepths[445] = 0; // obj_key_res
global.__objectDepths[446] = 0; // obj_goomba_res
global.__objectDepths[447] = 0; // obj_goombrat_res
global.__objectDepths[448] = 0; // obj_koopa_res
global.__objectDepths[449] = 0; // obj_koopa_red_res
global.__objectDepths[450] = 0; // obj_buzzybeetle_res
global.__objectDepths[451] = 0; // obj_spiny_res
global.__objectDepths[452] = 0; // obj_mechakoopa_res
global.__objectDepths[453] = 0; // obj_tuberia_res
global.__objectDepths[454] = 0; // obj_angrysun_res
global.__objectDepths[455] = 0; // obj_floruga_res
global.__objectDepths[456] = 0; // obj_floruga_angry_res
global.__objectDepths[457] = 0; // obj_drybones_res
global.__objectDepths[458] = 0; // obj_shell_drybones_res
global.__objectDepths[459] = 0; // obj_spiny_shell_res
global.__objectDepths[460] = 0; // obj_buzzy_shell_res
global.__objectDepths[461] = 0; // obj_donut_res
global.__objectDepths[462] = 0; // obj_blooper_res
global.__objectDepths[463] = 0; // obj_hammerbro_res
global.__objectDepths[464] = 0; // obj_sledgebro_res
global.__objectDepths[465] = 0; // obj_boomboom_res
global.__objectDepths[466] = 0; // obj_thwomp_res
global.__objectDepths[467] = -1; // obj_grinder_res
global.__objectDepths[468] = -1; // obj_bumper_res
global.__objectDepths[469] = 0; // obj_bobomb_res
global.__objectDepths[470] = 0; // obj_bobomb_ready_res
global.__objectDepths[471] = 0; // obj_bullebill_base_res
global.__objectDepths[472] = 0; // obj_bullebill_base_red_res
global.__objectDepths[473] = 0; // obj_cannon_res
global.__objectDepths[474] = 0; // obj_cannon_red_res
global.__objectDepths[475] = 0; // obj_soplete_res
global.__objectDepths[476] = 0; // obj_monty_res
global.__objectDepths[477] = 0; // obj_1up_res
global.__objectDepths[478] = 0; // obj_mushroom_res
global.__objectDepths[479] = 0; // obj_fireflower_res
global.__objectDepths[480] = 0; // obj_frogsuit_res
global.__objectDepths[481] = 0; // obj_hen_mushroom_res
global.__objectDepths[482] = 0; // obj_superflower_res
global.__objectDepths[483] = 0; // obj_cap_res
global.__objectDepths[484] = 0; // obj_star_res
global.__objectDepths[485] = 0; // obj_spring_res
global.__objectDepths[486] = 0; // obj_spring_land_res
global.__objectDepths[487] = 0; // obj_qblock_res
global.__objectDepths[488] = 0; // obj_block_hidden_res
global.__objectDepths[489] = 0; // obj_block_res
global.__objectDepths[490] = 0; // obj_noteblock_res
global.__objectDepths[491] = 0; // obj_musicblock_res
global.__objectDepths[492] = 0; // obj_pplant_res
global.__objectDepths[493] = 0; // obj_plant_fire_res
global.__objectDepths[494] = -1; // obj_muncher_res
global.__objectDepths[495] = 0; // obj_billbanzai_res
global.__objectDepths[496] = 0; // obj_spike_res
global.__objectDepths[497] = 0; // obj_spike_ball_res
global.__objectDepths[498] = 0; // obj_torbellino_res
global.__objectDepths[499] = 0; // obj_onoffblock_res
global.__objectDepths[500] = 0; // obj_onoffplatform_res
global.__objectDepths[501] = 0; // obj_onoffplatform_blue_res
global.__objectDepths[502] = 0; // obj_pblock_res
global.__objectDepths[503] = 0; // obj_pblock2_res
global.__objectDepths[504] = 0; // obj_chainchomp_res
global.__objectDepths[505] = 0; // obj_boo_res
global.__objectDepths[506] = 0; // obj_pinchos_res
global.__objectDepths[507] = 0; // obj_nube_res
global.__objectDepths[508] = 1; // obj_oneway_res
global.__objectDepths[509] = 0; // obj_checkpoint_res
global.__objectDepths[510] = 1; // obj_door_res
global.__objectDepths[511] = 1; // obj_door_exit_res
global.__objectDepths[512] = 1; // obj_door_switch_res
global.__objectDepths[513] = 1; // obj_door_switch_exit_res
global.__objectDepths[514] = 1; // obj_door_lock_res
global.__objectDepths[515] = 1; // obj_door_lock_exit_res
global.__objectDepths[516] = 0; // obj_clown_res
global.__objectDepths[517] = 0; // obj_clown_fire_res
global.__objectDepths[518] = 0; // obj_egg_res
global.__objectDepths[519] = 0; // obj_egg_red_res
global.__objectDepths[520] = 0; // obj_podoboo_res
global.__objectDepths[521] = 0; // obj_estalactita_res
global.__objectDepths[522] = 0; // obj_estalactita2_res
global.__objectDepths[523] = 0; // obj_cheepcheep_res
global.__objectDepths[524] = 0; // obj_cheepcheep2_res
global.__objectDepths[525] = 0; // obj_arrow_res
global.__objectDepths[526] = 0; // obj_magikoopa_res
global.__objectDepths[527] = 0; // obj_lava_lift_res
global.__objectDepths[528] = 0; // obj_fast_lava_lift_res
global.__objectDepths[529] = 2; // obj_vine_res
global.__objectDepths[530] = 0; // obj_pokey_res
global.__objectDepths[531] = 271; // obj_semisolid_platform1
global.__objectDepths[532] = 8; // obj_mushroom_platform_res
global.__objectDepths[533] = 270; // obj_puente_res
global.__objectDepths[534] = -1; // obj_platform_res
global.__objectDepths[535] = 0; // obj_platform_blue_res
global.__objectDepths[536] = -1; // obj_cinta_res
global.__objectDepths[537] = -1; // obj_cinta_on_res
global.__objectDepths[538] = -7; // obj_efecto_sonido
global.__objectDepths[539] = -7; // obj_efecto_musica
global.__objectDepths[540] = 0; // obj_parent_sound_o
global.__objectDepths[541] = 0; // obj_original_risas
global.__objectDepths[542] = 0; // obj_original_gloria
global.__objectDepths[543] = 0; // obj_original_risa_grande
global.__objectDepths[544] = 0; // obj_original_bombilla
global.__objectDepths[545] = 0; // obj_original_error
global.__objectDepths[546] = 0; // obj_original_nota_musical
global.__objectDepths[547] = 0; // obj_original_ahh
global.__objectDepths[548] = 0; // obj_original_ubsi
global.__objectDepths[549] = 0; // obj_original_auh
global.__objectDepths[550] = 0; // obj_original_uhh
global.__objectDepths[551] = 0; // obj_original_golpe_gato
global.__objectDepths[552] = 0; // obj_original_cerdito
global.__objectDepths[553] = 0; // obj_original_derrumbe
global.__objectDepths[554] = 0; // obj_original_ovacion
global.__objectDepths[555] = 0; // obj_original_calavera
global.__objectDepths[556] = 0; // obj_original_guitarra
global.__objectDepths[557] = 0; // obj_original_farolillos
global.__objectDepths[558] = 0; // obj_original_insecto
global.__objectDepths[559] = 0; // obj_original_serpentina_grande
global.__objectDepths[560] = 0; // obj_original_serpentina
global.__objectDepths[561] = 0; // obj_original_conmocion
global.__objectDepths[562] = 0; // obj_original_fuegos
global.__objectDepths[563] = 0; // obj_original_n64
global.__objectDepths[564] = 0; // obj_original_bowser
global.__objectDepths[565] = 0; // obj_original_bowserjr
global.__objectDepths[566] = -7; // obj_risas_snd_res
global.__objectDepths[567] = -7; // obj_risas_grande_snd_res
global.__objectDepths[568] = -7; // obj_gloria_snd_res
global.__objectDepths[569] = -7; // obj_bombilla_snd_res
global.__objectDepths[570] = -7; // obj_error_snd_res
global.__objectDepths[571] = -7; // obj_nota_musical_snd_res
global.__objectDepths[572] = -7; // obj_ahh_snd_res
global.__objectDepths[573] = -7; // obj_ubsi_snd_res
global.__objectDepths[574] = -7; // obj_insecto_snd_res
global.__objectDepths[575] = -7; // obj_auh_snd_res
global.__objectDepths[576] = -7; // obj_uhh_snd_res
global.__objectDepths[577] = -7; // obj_golpe_gato_snd_res
global.__objectDepths[578] = -7; // obj_cerdito_snd_res
global.__objectDepths[579] = -7; // obj_calavera_snd_res
global.__objectDepths[580] = -7; // obj_serpentina_snd_res
global.__objectDepths[581] = -7; // obj_serpentina_grande_snd_res
global.__objectDepths[582] = -7; // obj_conmocion_snd_res
global.__objectDepths[583] = -7; // obj_derrumbe_snd_res
global.__objectDepths[584] = -7; // obj_fuegos_snd_res
global.__objectDepths[585] = -7; // obj_ovacion_snd_res
global.__objectDepths[586] = -7; // obj_guitarra_snd_res
global.__objectDepths[587] = -7; // obj_farolillos_snd_res
global.__objectDepths[588] = -7; // obj_n64_snd_res
global.__objectDepths[589] = -7; // obj_bowser_snd_res
global.__objectDepths[590] = -7; // obj_bowserjr_snd_res
global.__objectDepths[591] = -10; // obj_panel_expand
global.__objectDepths[592] = -11; // obj_button_close
global.__objectDepths[593] = -11; // obj_next_before
global.__objectDepths[594] = -11; // obj_panel_circle
global.__objectDepths[595] = -12; // obj_card_circle
global.__objectDepths[596] = -9; // obj_water_draw
global.__objectDepths[597] = -10; // obj_water_move
global.__objectDepths[598] = -11; // obj_water_move_limit
global.__objectDepths[599] = -11; // obj_bt_close_water
global.__objectDepths[600] = -6; // obj_water_level_control
global.__objectDepths[601] = -7; // obj_lava_water
global.__objectDepths[602] = -20; // obj_lava_water_drybones
global.__objectDepths[603] = -12; // obj_ventana_water
global.__objectDepths[604] = -13; // obj_button_speed_water
global.__objectDepths[605] = -12; // obj_ventana
global.__objectDepths[606] = -13; // obj_window_button
global.__objectDepths[607] = -13; // obj_button_wings
global.__objectDepths[608] = -6; // obj_modo_sonidos_control
global.__objectDepths[609] = 0; // obj_change_world
global.__objectDepths[610] = -9; // obj_editormanager
global.__objectDepths[611] = -8; // obj_mario_editor
global.__objectDepths[612] = 0; // obj_parent_layout
global.__objectDepths[613] = 0; // obj_parent_save
global.__objectDepths[614] = 0; // obj_parent_resource
global.__objectDepths[615] = -7; // obj_parent_sounds
global.__objectDepths[616] = 15; // obj_creation_preview
global.__objectDepths[617] = 0; // obj_resource_empty
global.__objectDepths[618] = -26; // obj_cursor
global.__objectDepths[619] = 369; // obj_grid
global.__objectDepths[620] = 0; // obj_player_trail
global.__objectDepths[621] = -20; // obj_effect_touch
global.__objectDepths[622] = 0; // obj_arrow_lock
global.__objectDepths[623] = -12; // obj_button_trail
global.__objectDepths[624] = 0; // obj_call_mario
global.__objectDepths[625] = 0; // obj_silbido
global.__objectDepths[626] = 293; // obj_shadow
global.__objectDepths[627] = 0; // obj_uni_parent_sizabledraw
global.__objectDepths[628] = 0; // obj_editor_title
global.__objectDepths[629] = 0; // obj_parent_sizabledraw
global.__objectDepths[630] = -23; // obj_change_view


global.__objectNames[0] = "obj_lighting";
global.__objectNames[1] = "obj_flagpole";
global.__objectNames[2] = "obj_SMB_flag";
global.__objectNames[3] = "obj_score_flag";
global.__objectNames[4] = "obj_SMB_castle";
global.__objectNames[5] = "obj_SMB_castle_front";
global.__objectNames[6] = "obj_mini_flag";
global.__objectNames[7] = "obj_goalcard";
global.__objectNames[8] = "obj_goalcard_get";
global.__objectNames[9] = "obj_goalgate";
global.__objectNames[10] = "obj_goalgate_front";
global.__objectNames[11] = "obj_goalgate_tape";
global.__objectNames[12] = "obj_crystalorb";
global.__objectNames[13] = "obj_hawmask";
global.__objectNames[14] = "obj_mario";
global.__objectNames[15] = "obj_marioU";
global.__objectNames[16] = "obj_checkpoint";
global.__objectNames[17] = "obj_levelmanager";
global.__objectNames[18] = "obj_autoscroll";
global.__objectNames[19] = "obj_bganimator";
global.__objectNames[20] = "obj_warpmario";
global.__objectNames[21] = "obj_shake_mario";
global.__objectNames[22] = "obj_platform_help";
global.__objectNames[23] = "obj_stormmaker";
global.__objectNames[24] = "obj_fallow_view";
global.__objectNames[25] = "obj_galoomba";
global.__objectNames[26] = "obj_galoomba2";
global.__objectNames[27] = "obj_shoegoomba";
global.__objectNames[28] = "obj_koopa";
global.__objectNames[29] = "obj_koopa_red";
global.__objectNames[30] = "obj_beachkoopa";
global.__objectNames[31] = "obj_beachkoopa_red";
global.__objectNames[32] = "obj_floruga";
global.__objectNames[33] = "obj_floruga_body";
global.__objectNames[34] = "obj_buzzybeetle";
global.__objectNames[35] = "obj_spiny";
global.__objectNames[36] = "obj_buzzy_ceiling";
global.__objectNames[37] = "obj_jumppiranha";
global.__objectNames[38] = "obj_plant_fire";
global.__objectNames[39] = "obj_spiketop";
global.__objectNames[40] = "obj_cheepcheep";
global.__objectNames[41] = "obj_cheepcheep2";
global.__objectNames[42] = "obj_blooper";
global.__objectNames[43] = "obj_angrysun";
global.__objectNames[44] = "obj_happymoon";
global.__objectNames[45] = "obj_monty_chase";
global.__objectNames[46] = "obj_spike";
global.__objectNames[47] = "obj_spike_ball";
global.__objectNames[48] = "obj_snow_ball";
global.__objectNames[49] = "obj_snow_ball_held";
global.__objectNames[50] = "obj_pokey";
global.__objectNames[51] = "obj_boo";
global.__objectNames[52] = "obj_mechakoopa_held";
global.__objectNames[53] = "obj_mechakoopa_debris";
global.__objectNames[54] = "obj_blastakoopa_bullet";
global.__objectNames[55] = "obj_zappakoopa_beam";
global.__objectNames[56] = "obj_zappakoopa_beameff";
global.__objectNames[57] = "obj_zappakoopa_laser";
global.__objectNames[58] = "obj_mechakoopa";
global.__objectNames[59] = "obj_blastakoopa";
global.__objectNames[60] = "obj_zappakoopa";
global.__objectNames[61] = "obj_drybones";
global.__objectNames[62] = "obj_thwomp";
global.__objectNames[63] = "obj_thwomp_2";
global.__objectNames[64] = "obj_podoboo";
global.__objectNames[65] = "obj_grinder";
global.__objectNames[66] = "obj_magikoopa";
global.__objectNames[67] = "obj_bobomb";
global.__objectNames[68] = "obj_bobomb_big";
global.__objectNames[69] = "obj_bobomb_ready";
global.__objectNames[70] = "obj_bullebill_base";
global.__objectNames[71] = "obj_bullebill_base_red";
global.__objectNames[72] = "obj_bulletbill";
global.__objectNames[73] = "obj_bulletbull_red";
global.__objectNames[74] = "obj_banzaibill";
global.__objectNames[75] = "obj_rockywrench";
global.__objectNames[76] = "obj_cannon";
global.__objectNames[77] = "obj_cannon_red";
global.__objectNames[78] = "obj_soplete";
global.__objectNames[79] = "obj_soplete_alt";
global.__objectNames[80] = "obj_chain_chomp_free";
global.__objectNames[81] = "obj_SMB_bowser";
global.__objectNames[82] = "obj_bowser";
global.__objectNames[83] = "obj_boomboom";
global.__objectNames[84] = "obj_hammerbro";
global.__objectNames[85] = "obj_sledgebro";
global.__objectNames[86] = "obj_charginchuck";
global.__objectNames[87] = "obj_wings_dead";
global.__objectNames[88] = "obj_paracaidas_dead";
global.__objectNames[89] = "obj_paracaidas_go";
global.__objectNames[90] = "obj_solid";
global.__objectNames[91] = "obj_solidtop";
global.__objectNames[92] = "obj_climb";
global.__objectNames[93] = "obj_climb_net";
global.__objectNames[94] = "obj_swim";
global.__objectNames[95] = "obj_slippery";
global.__objectNames[96] = "obj_hurtsolid";
global.__objectNames[97] = "obj_hurtsolid2";
global.__objectNames[98] = "obj_slope_r";
global.__objectNames[99] = "obj_slope_l";
global.__objectNames[100] = "obj_slope_sr";
global.__objectNames[101] = "obj_slope_sl";
global.__objectNames[102] = "obj_islope_r";
global.__objectNames[103] = "obj_islope_l";
global.__objectNames[104] = "obj_islope_sr";
global.__objectNames[105] = "obj_islope_sl";
global.__objectNames[106] = "obj_fillwater";
global.__objectNames[107] = "obj_stopblock";
global.__objectNames[108] = "obj_block";
global.__objectNames[109] = "obj_block_multicoin";
global.__objectNames[110] = "obj_block_coinchain";
global.__objectNames[111] = "obj_block_hidden";
global.__objectNames[112] = "obj_flipblock";
global.__objectNames[113] = "obj_noteblock";
global.__objectNames[114] = "obj_musicblock";
global.__objectNames[115] = "obj_onoffblock";
global.__objectNames[116] = "obj_onoffplatform";
global.__objectNames[117] = "obj_onoffplatform_blue";
global.__objectNames[118] = "obj_block_rock";
global.__objectNames[119] = "obj_block_ice";
global.__objectNames[120] = "obj_pblock";
global.__objectNames[121] = "obj_anti_pblock";
global.__objectNames[122] = "obj_nube";
global.__objectNames[123] = "obj_vine_green";
global.__objectNames[124] = "obj_beanstalk";
global.__objectNames[125] = "obj_vine";
global.__objectNames[126] = "obj_muncher";
global.__objectNames[127] = "obj_muncher_big";
global.__objectNames[128] = "obj_pinchos";
global.__objectNames[129] = "obj_berry";
global.__objectNames[130] = "obj_estalactita";
global.__objectNames[131] = "obj_estalactita2";
global.__objectNames[132] = "obj_arrow";
global.__objectNames[133] = "obj_cinta_parent";
global.__objectNames[134] = "obj_cinta";
global.__objectNames[135] = "obj_cinta_switch";
global.__objectNames[136] = "obj_plataforma";
global.__objectNames[137] = "obj_plataforma_blue";
global.__objectNames[138] = "obj_donut";
global.__objectNames[139] = "obj_fast_lava_lift";
global.__objectNames[140] = "obj_lava_lift";
global.__objectNames[141] = "obj_lava_lift_part";
global.__objectNames[142] = "obj_coin";
global.__objectNames[143] = "obj_icecoin";
global.__objectNames[144] = "obj_pink_coin";
global.__objectNames[145] = "obj_coin10";
global.__objectNames[146] = "obj_coin30";
global.__objectNames[147] = "obj_coin50";
global.__objectNames[148] = "obj_spring";
global.__objectNames[149] = "obj_spring_land";
global.__objectNames[150] = "obj_coin_pow";
global.__objectNames[151] = "obj_coin_pow_big";
global.__objectNames[152] = "obj_pswitch";
global.__objectNames[153] = "obj_pswitch_press";
global.__objectNames[154] = "obj_block_pow_hold";
global.__objectNames[155] = "obj_quicksand";
global.__objectNames[156] = "obj_bumper";
global.__objectNames[157] = "obj_onewaygate_right";
global.__objectNames[158] = "obj_onewaygate_left";
global.__objectNames[159] = "obj_onewaygate_top";
global.__objectNames[160] = "obj_onewaygate_bottom";
global.__objectNames[161] = "obj_key";
global.__objectNames[162] = "obj_key_appear";
global.__objectNames[163] = "obj_key_fallow";
global.__objectNames[164] = "obj_torbellino";
global.__objectNames[165] = "obj_bortice";
global.__objectNames[166] = "obj_tuberia";
global.__objectNames[167] = "obj_door";
global.__objectNames[168] = "obj_door_exit";
global.__objectNames[169] = "obj_door_switch";
global.__objectNames[170] = "obj_door_switch_exit";
global.__objectNames[171] = "obj_door_lock";
global.__objectNames[172] = "obj_door_lock_exit";
global.__objectNames[173] = "obj_deactivation";
global.__objectNames[174] = "obj_physicsparent";
global.__objectNames[175] = "obj_powerupparent";
global.__objectNames[176] = "obj_enemyparent";
global.__objectNames[177] = "obj_deactenemyparent";
global.__objectNames[178] = "obj_bossparent";
global.__objectNames[179] = "obj_blockparent";
global.__objectNames[180] = "obj_worldparent";
global.__objectNames[181] = "obj_panelparent";
global.__objectNames[182] = "obj_holdparent";
global.__objectNames[183] = "obj_parcarry";
global.__objectNames[184] = "obj_slopeparent";
global.__objectNames[185] = "obj_enemyparent_held";
global.__objectNames[186] = "obj_enemyparent_lava";
global.__objectNames[187] = "obj_deadmario";
global.__objectNames[188] = "obj_doormario";
global.__objectNames[189] = "obj_puller";
global.__objectNames[190] = "obj_player_goal_smb1";
global.__objectNames[191] = "obj_player_goal_smb3";
global.__objectNames[192] = "obj_player_goal_smw";
global.__objectNames[193] = "obj_player_goal_smw_castle";
global.__objectNames[194] = "obj_player_goal_smb2";
global.__objectNames[195] = "obj_slider";
global.__objectNames[196] = "obj_spinner";
global.__objectNames[197] = "obj_mario_transform2";
global.__objectNames[198] = "obj_1up";
global.__objectNames[199] = "obj_mushroom";
global.__objectNames[200] = "obj_fireflower";
global.__objectNames[201] = "obj_turnip";
global.__objectNames[202] = "obj_superflower";
global.__objectNames[203] = "obj_cap";
global.__objectNames[204] = "obj_megamushroom";
global.__objectNames[205] = "obj_hen_mushroom";
global.__objectNames[206] = "obj_star";
global.__objectNames[207] = "obj_frogsuit";
global.__objectNames[208] = "obj_iceflower";
global.__objectNames[209] = "obj_blueshell";
global.__objectNames[210] = "obj_penguinsuit";
global.__objectNames[211] = "obj_propellershroom";
global.__objectNames[212] = "obj_boomerangflower";
global.__objectNames[213] = "obj_acorn";
global.__objectNames[214] = "obj_egg";
global.__objectNames[215] = "obj_egg_hatch";
global.__objectNames[216] = "obj_yoshi2";
global.__objectNames[217] = "obj_yoshi_runaway";
global.__objectNames[218] = "obj_yoshi_abandon";
global.__objectNames[219] = "obj_yoshifire";
global.__objectNames[220] = "obj_yoshifire_purple";
global.__objectNames[221] = "obj_yoshifire_one";
global.__objectNames[222] = "obj_tongue";
global.__objectNames[223] = "obj_egg_red";
global.__objectNames[224] = "obj_yoshi_red";
global.__objectNames[225] = "obj_getshoe";
global.__objectNames[226] = "obj_kuriboshoe";
global.__objectNames[227] = "obj_kuriboshoe2";
global.__objectNames[228] = "obj_smoke_shoe";
global.__objectNames[229] = "obj_kuriboshoe_movement";
global.__objectNames[230] = "obj_kuribo_drybones";
global.__objectNames[231] = "obj_helmet";
global.__objectNames[232] = "obj_helmet_spiny";
global.__objectNames[233] = "obj_clown";
global.__objectNames[234] = "obj_clown_fire";
global.__objectNames[235] = "obj_fire_clown";
global.__objectNames[236] = "obj_fire_clown_small";
global.__objectNames[237] = "obj_clown_smoke";
global.__objectNames[238] = "obj_clown_explotion";
global.__objectNames[239] = "obj_cap_mario";
global.__objectNames[240] = "obj_powerupsprout";
global.__objectNames[241] = "obj_fireball";
global.__objectNames[242] = "obj_superball";
global.__objectNames[243] = "obj_superball_trail";
global.__objectNames[244] = "obj_invincibility";
global.__objectNames[245] = "obj_brohammer_yoshi";
global.__objectNames[246] = "obj_bones_yoshi";
global.__objectNames[247] = "obj_bones_yoshi_one";
global.__objectNames[248] = "obj_galoomba_hold";
global.__objectNames[249] = "obj_galoomba_hold2";
global.__objectNames[250] = "obj_plantfire";
global.__objectNames[251] = "obj_espina";
global.__objectNames[252] = "obj_angrysun_movement";
global.__objectNames[253] = "obj_crumblebones";
global.__objectNames[254] = "obj_magic";
global.__objectNames[255] = "obj_bone";
global.__objectNames[256] = "obj_bobomb_hold";
global.__objectNames[257] = "obj_cannonball";
global.__objectNames[258] = "obj_cannonball_red";
global.__objectNames[259] = "obj_wrench";
global.__objectNames[260] = "obj_bowser_fire";
global.__objectNames[261] = "obj_bowserfire_up";
global.__objectNames[262] = "obj_bowser_fire_down";
global.__objectNames[263] = "obj_enemy_dead";
global.__objectNames[264] = "obj_enemy_dead_castle";
global.__objectNames[265] = "obj_enemy_multidead";
global.__objectNames[266] = "obj_stomped";
global.__objectNames[267] = "obj_shell";
global.__objectNames[268] = "obj_shell_held";
global.__objectNames[269] = "obj_shell_kamikaze";
global.__objectNames[270] = "obj_shell_empty";
global.__objectNames[271] = "obj_spiny_empty";
global.__objectNames[272] = "obj_shell_drybones";
global.__objectNames[273] = "obj_shell_drybones_held";
global.__objectNames[274] = "obj_brohammer";
global.__objectNames[275] = "obj_blockcoin";
global.__objectNames[276] = "obj_coinchain";
global.__objectNames[277] = "obj_shard";
global.__objectNames[278] = "obj_veggiecoin";
global.__objectNames[279] = "obj_multiveggiecoin";
global.__objectNames[280] = "obj_coinchange";
global.__objectNames[281] = "obj_blownbubble";
global.__objectNames[282] = "obj_veggies_pull";
global.__objectNames[283] = "obj_curtainin";
global.__objectNames[284] = "obj_curtainout";
global.__objectNames[285] = "obj_fadein";
global.__objectNames[286] = "obj_fadeout";
global.__objectNames[287] = "obj_score";
global.__objectNames[288] = "obj_smoke";
global.__objectNames[289] = "obj_statuesmoke";
global.__objectNames[290] = "obj_spinsmoke";
global.__objectNames[291] = "obj_spinthump";
global.__objectNames[292] = "obj_bubble";
global.__objectNames[293] = "obj_sparkletrail";
global.__objectNames[294] = "obj_sparkles_coin";
global.__objectNames[295] = "obj_scoregoal";
global.__objectNames[296] = "obj_smoke_cap";
global.__objectNames[297] = "obj_detroy_enemy";
global.__objectNames[298] = "obj_rotten_signal";
global.__objectNames[299] = "obj_gotas";
global.__objectNames[300] = "obj_menu_pausa";
global.__objectNames[301] = "obj_pausa_button";
global.__objectNames[302] = "obj_button_sonidos_pausa";
global.__objectNames[303] = "obj_axe_smw";
global.__objectNames[304] = "obj_castle_floor";
global.__objectNames[305] = "obj_castle";
global.__objectNames[306] = "obj_castle_front";
global.__objectNames[307] = "obj_explosion";
global.__objectNames[308] = "obj_blockbumper";
global.__objectNames[309] = "obj_stomp";
global.__objectNames[310] = "obj_settings_panel";
global.__objectNames[311] = "obj_configurar_controles";
global.__objectNames[312] = "obj_button_settings_estrella";
global.__objectNames[313] = "obj_button_settings_idioma";
global.__objectNames[314] = "obj_button_settings_sm4j";
global.__objectNames[315] = "obj_button_settings_sonidos";
global.__objectNames[316] = "obj_selecting_player";
global.__objectNames[317] = "obj_window_select";
global.__objectNames[318] = "obj_button_settings_close";
global.__objectNames[319] = "obj_key_br";
global.__objectNames[320] = "obj_inhibidor_vk";
global.__objectNames[321] = "obj_sidefade";
global.__objectNames[322] = "obj_intro_control";
global.__objectNames[323] = "obj_title_controller";
global.__objectNames[324] = "obj_title_oprime";
global.__objectNames[325] = "obj_editor_screen";
global.__objectNames[326] = "obj_play_screen";
global.__objectNames[327] = "obj_load_level";
global.__objectNames[328] = "obj_persistent";
global.__objectNames[329] = "obj_mariostart";
global.__objectNames[330] = "obj_mariostart_mario";
global.__objectNames[331] = "obj_arrow_big";
global.__objectNames[332] = "object556";
global.__objectNames[333] = "obj_cursor_mask";
global.__objectNames[334] = "obj_d_pad";
global.__objectNames[335] = "obj_DSM_control";
global.__objectNames[336] = "obj_DSM_level";
global.__objectNames[337] = "obj_DSM_mario";
global.__objectNames[338] = "obj_DSM_button";
global.__objectNames[339] = "obj_castle_start";
global.__objectNames[340] = "obj_guardabot";
global.__objectNames[341] = "obj_load_guardabot";
global.__objectNames[342] = "obj_gb_button";
global.__objectNames[343] = "obj_bt_gb_next";
global.__objectNames[344] = "obj_bt_gb_before";
global.__objectNames[345] = "obj_gb_level";
global.__objectNames[346] = "obj_bt_gb_play";
global.__objectNames[347] = "obj_bt_gb_delete";
global.__objectNames[348] = "obj_bt_gb_close";
global.__objectNames[349] = "obj_input_name_user";
global.__objectNames[350] = "obj_input_password";
global.__objectNames[351] = "obj_button_name_user";
global.__objectNames[352] = "obj_button_save_id";
global.__objectNames[353] = "obj_superado_bg";
global.__objectNames[354] = "obj_button_superado";
global.__objectNames[355] = "obj_game_over";
global.__objectNames[356] = "obj_time_up";
global.__objectNames[357] = "obj_button_start";
global.__objectNames[358] = "obj_button_back";
global.__objectNames[359] = "obj_button_niveles_mundiales";
global.__objectNames[360] = "obj_SMB1_walk";
global.__objectNames[361] = "obj_desafio_munchers";
global.__objectNames[362] = "obj_mario_victory";
global.__objectNames[363] = "obj_princess";
global.__objectNames[364] = "obj_apariencia";
global.__objectNames[365] = "obj_card_logo";
global.__objectNames[366] = "obj_bg_selection";
global.__objectNames[367] = "obj_bg1";
global.__objectNames[368] = "obj_time";
global.__objectNames[369] = "obj_button_ok";
global.__objectNames[370] = "obj_button_time";
global.__objectNames[371] = "obj_autoavance";
global.__objectNames[372] = "obj_button_autoavance";
global.__objectNames[373] = "obj_condiciones";
global.__objectNames[374] = "obj_condiciones_button";
global.__objectNames[375] = "obj_tabs_condiciones";
global.__objectNames[376] = "obj_alert_condicion";
global.__objectNames[377] = "obj_card_expand";
global.__objectNames[378] = "obj_button_home";
global.__objectNames[379] = "obj_edit_menu";
global.__objectNames[380] = "obj_button_paloma";
global.__objectNames[381] = "obj_settings_button";
global.__objectNames[382] = "obj_button_close_menu";
global.__objectNames[383] = "obj_ground2";
global.__objectNames[384] = "obj_ground3";
global.__objectNames[385] = "obj_panel_save_load";
global.__objectNames[386] = "obj_button_save_load";
global.__objectNames[387] = "obj_button_save_changes";
global.__objectNames[388] = "obj_panel_list";
global.__objectNames[389] = "obj_list_item";
global.__objectNames[390] = "obj_alert_load";
global.__objectNames[391] = "obj_noti_load_button";
global.__objectNames[392] = "obj_bt_load_next";
global.__objectNames[393] = "obj_bt_load_before";
global.__objectNames[394] = "obj_load_image";
global.__objectNames[395] = "obj_window_alert";
global.__objectNames[396] = "obj_button_notification_aceptar";
global.__objectNames[397] = "obj_button_notification_cancelar";
global.__objectNames[398] = "obj_input";
global.__objectNames[399] = "obj_toast";
global.__objectNames[400] = "obj_etiquetas";
global.__objectNames[401] = "obj_ground_title";
global.__objectNames[402] = "obj_creator_jugar_editar";
global.__objectNames[403] = "obj_menu_editor";
global.__objectNames[404] = "obj_menu_editor_ext";
global.__objectNames[405] = "obj_robot";
global.__objectNames[406] = "obj_erase";
global.__objectNames[407] = "obj_card_block_sounds";
global.__objectNames[408] = "obj_logo_game";
global.__objectNames[409] = "obj_card_bg";
global.__objectNames[410] = "obj_card_bout";
global.__objectNames[411] = "obj_card_autoavance";
global.__objectNames[412] = "obj_panel_time";
global.__objectNames[413] = "obj_card_condiciones";
global.__objectNames[414] = "obj_card_rocket";
global.__objectNames[415] = "obj_expand";
global.__objectNames[416] = "obj_dog";
global.__objectNames[417] = "obj_card_item";
global.__objectNames[418] = "obj_lave_draw";
global.__objectNames[419] = "obj_panel_left";
global.__objectNames[420] = "obj_night_change";
global.__objectNames[421] = "obj_expand_panels";
global.__objectNames[422] = "obj_expand_panels_left";
global.__objectNames[423] = "obj_expand_paneles_top";
global.__objectNames[424] = "obj_rocket_anim";
global.__objectNames[425] = "obj_decoracion_1";
global.__objectNames[426] = "obj_decoracion_2";
global.__objectNames[427] = "obj_decoracion_3";
global.__objectNames[428] = "obj_decoracion_4";
global.__objectNames[429] = "obj_decoracion_parent";
global.__objectNames[430] = "obj_modelbgo";
global.__objectNames[431] = "obj_modelsolid";
global.__objectNames[432] = "obj_modelsizable";
global.__objectNames[433] = "obj_ground";
global.__objectNames[434] = "obj_tile_trigger";
global.__objectNames[435] = "obj_pswitch_res";
global.__objectNames[436] = "obj_pow_res";
global.__objectNames[437] = "obj_rock_res";
global.__objectNames[438] = "obj_ice_res";
global.__objectNames[439] = "obj_coin_res";
global.__objectNames[440] = "obj_icecoin_res";
global.__objectNames[441] = "obj_pink_coin_res";
global.__objectNames[442] = "obj_coin10_res";
global.__objectNames[443] = "obj_coin30_res";
global.__objectNames[444] = "obj_coin50_res";
global.__objectNames[445] = "obj_key_res";
global.__objectNames[446] = "obj_goomba_res";
global.__objectNames[447] = "obj_goombrat_res";
global.__objectNames[448] = "obj_koopa_res";
global.__objectNames[449] = "obj_koopa_red_res";
global.__objectNames[450] = "obj_buzzybeetle_res";
global.__objectNames[451] = "obj_spiny_res";
global.__objectNames[452] = "obj_mechakoopa_res";
global.__objectNames[453] = "obj_tuberia_res";
global.__objectNames[454] = "obj_angrysun_res";
global.__objectNames[455] = "obj_floruga_res";
global.__objectNames[456] = "obj_floruga_angry_res";
global.__objectNames[457] = "obj_drybones_res";
global.__objectNames[458] = "obj_shell_drybones_res";
global.__objectNames[459] = "obj_spiny_shell_res";
global.__objectNames[460] = "obj_buzzy_shell_res";
global.__objectNames[461] = "obj_donut_res";
global.__objectNames[462] = "obj_blooper_res";
global.__objectNames[463] = "obj_hammerbro_res";
global.__objectNames[464] = "obj_sledgebro_res";
global.__objectNames[465] = "obj_boomboom_res";
global.__objectNames[466] = "obj_thwomp_res";
global.__objectNames[467] = "obj_grinder_res";
global.__objectNames[468] = "obj_bumper_res";
global.__objectNames[469] = "obj_bobomb_res";
global.__objectNames[470] = "obj_bobomb_ready_res";
global.__objectNames[471] = "obj_bullebill_base_res";
global.__objectNames[472] = "obj_bullebill_base_red_res";
global.__objectNames[473] = "obj_cannon_res";
global.__objectNames[474] = "obj_cannon_red_res";
global.__objectNames[475] = "obj_soplete_res";
global.__objectNames[476] = "obj_monty_res";
global.__objectNames[477] = "obj_1up_res";
global.__objectNames[478] = "obj_mushroom_res";
global.__objectNames[479] = "obj_fireflower_res";
global.__objectNames[480] = "obj_frogsuit_res";
global.__objectNames[481] = "obj_hen_mushroom_res";
global.__objectNames[482] = "obj_superflower_res";
global.__objectNames[483] = "obj_cap_res";
global.__objectNames[484] = "obj_star_res";
global.__objectNames[485] = "obj_spring_res";
global.__objectNames[486] = "obj_spring_land_res";
global.__objectNames[487] = "obj_qblock_res";
global.__objectNames[488] = "obj_block_hidden_res";
global.__objectNames[489] = "obj_block_res";
global.__objectNames[490] = "obj_noteblock_res";
global.__objectNames[491] = "obj_musicblock_res";
global.__objectNames[492] = "obj_pplant_res";
global.__objectNames[493] = "obj_plant_fire_res";
global.__objectNames[494] = "obj_muncher_res";
global.__objectNames[495] = "obj_billbanzai_res";
global.__objectNames[496] = "obj_spike_res";
global.__objectNames[497] = "obj_spike_ball_res";
global.__objectNames[498] = "obj_torbellino_res";
global.__objectNames[499] = "obj_onoffblock_res";
global.__objectNames[500] = "obj_onoffplatform_res";
global.__objectNames[501] = "obj_onoffplatform_blue_res";
global.__objectNames[502] = "obj_pblock_res";
global.__objectNames[503] = "obj_pblock2_res";
global.__objectNames[504] = "obj_chainchomp_res";
global.__objectNames[505] = "obj_boo_res";
global.__objectNames[506] = "obj_pinchos_res";
global.__objectNames[507] = "obj_nube_res";
global.__objectNames[508] = "obj_oneway_res";
global.__objectNames[509] = "obj_checkpoint_res";
global.__objectNames[510] = "obj_door_res";
global.__objectNames[511] = "obj_door_exit_res";
global.__objectNames[512] = "obj_door_switch_res";
global.__objectNames[513] = "obj_door_switch_exit_res";
global.__objectNames[514] = "obj_door_lock_res";
global.__objectNames[515] = "obj_door_lock_exit_res";
global.__objectNames[516] = "obj_clown_res";
global.__objectNames[517] = "obj_clown_fire_res";
global.__objectNames[518] = "obj_egg_res";
global.__objectNames[519] = "obj_egg_red_res";
global.__objectNames[520] = "obj_podoboo_res";
global.__objectNames[521] = "obj_estalactita_res";
global.__objectNames[522] = "obj_estalactita2_res";
global.__objectNames[523] = "obj_cheepcheep_res";
global.__objectNames[524] = "obj_cheepcheep2_res";
global.__objectNames[525] = "obj_arrow_res";
global.__objectNames[526] = "obj_magikoopa_res";
global.__objectNames[527] = "obj_lava_lift_res";
global.__objectNames[528] = "obj_fast_lava_lift_res";
global.__objectNames[529] = "obj_vine_res";
global.__objectNames[530] = "obj_pokey_res";
global.__objectNames[531] = "obj_semisolid_platform1";
global.__objectNames[532] = "obj_mushroom_platform_res";
global.__objectNames[533] = "obj_puente_res";
global.__objectNames[534] = "obj_platform_res";
global.__objectNames[535] = "obj_platform_blue_res";
global.__objectNames[536] = "obj_cinta_res";
global.__objectNames[537] = "obj_cinta_on_res";
global.__objectNames[538] = "obj_efecto_sonido";
global.__objectNames[539] = "obj_efecto_musica";
global.__objectNames[540] = "obj_parent_sound_o";
global.__objectNames[541] = "obj_original_risas";
global.__objectNames[542] = "obj_original_gloria";
global.__objectNames[543] = "obj_original_risa_grande";
global.__objectNames[544] = "obj_original_bombilla";
global.__objectNames[545] = "obj_original_error";
global.__objectNames[546] = "obj_original_nota_musical";
global.__objectNames[547] = "obj_original_ahh";
global.__objectNames[548] = "obj_original_ubsi";
global.__objectNames[549] = "obj_original_auh";
global.__objectNames[550] = "obj_original_uhh";
global.__objectNames[551] = "obj_original_golpe_gato";
global.__objectNames[552] = "obj_original_cerdito";
global.__objectNames[553] = "obj_original_derrumbe";
global.__objectNames[554] = "obj_original_ovacion";
global.__objectNames[555] = "obj_original_calavera";
global.__objectNames[556] = "obj_original_guitarra";
global.__objectNames[557] = "obj_original_farolillos";
global.__objectNames[558] = "obj_original_insecto";
global.__objectNames[559] = "obj_original_serpentina_grande";
global.__objectNames[560] = "obj_original_serpentina";
global.__objectNames[561] = "obj_original_conmocion";
global.__objectNames[562] = "obj_original_fuegos";
global.__objectNames[563] = "obj_original_n64";
global.__objectNames[564] = "obj_original_bowser";
global.__objectNames[565] = "obj_original_bowserjr";
global.__objectNames[566] = "obj_risas_snd_res";
global.__objectNames[567] = "obj_risas_grande_snd_res";
global.__objectNames[568] = "obj_gloria_snd_res";
global.__objectNames[569] = "obj_bombilla_snd_res";
global.__objectNames[570] = "obj_error_snd_res";
global.__objectNames[571] = "obj_nota_musical_snd_res";
global.__objectNames[572] = "obj_ahh_snd_res";
global.__objectNames[573] = "obj_ubsi_snd_res";
global.__objectNames[574] = "obj_insecto_snd_res";
global.__objectNames[575] = "obj_auh_snd_res";
global.__objectNames[576] = "obj_uhh_snd_res";
global.__objectNames[577] = "obj_golpe_gato_snd_res";
global.__objectNames[578] = "obj_cerdito_snd_res";
global.__objectNames[579] = "obj_calavera_snd_res";
global.__objectNames[580] = "obj_serpentina_snd_res";
global.__objectNames[581] = "obj_serpentina_grande_snd_res";
global.__objectNames[582] = "obj_conmocion_snd_res";
global.__objectNames[583] = "obj_derrumbe_snd_res";
global.__objectNames[584] = "obj_fuegos_snd_res";
global.__objectNames[585] = "obj_ovacion_snd_res";
global.__objectNames[586] = "obj_guitarra_snd_res";
global.__objectNames[587] = "obj_farolillos_snd_res";
global.__objectNames[588] = "obj_n64_snd_res";
global.__objectNames[589] = "obj_bowser_snd_res";
global.__objectNames[590] = "obj_bowserjr_snd_res";
global.__objectNames[591] = "obj_panel_expand";
global.__objectNames[592] = "obj_button_close";
global.__objectNames[593] = "obj_next_before";
global.__objectNames[594] = "obj_panel_circle";
global.__objectNames[595] = "obj_card_circle";
global.__objectNames[596] = "obj_water_draw";
global.__objectNames[597] = "obj_water_move";
global.__objectNames[598] = "obj_water_move_limit";
global.__objectNames[599] = "obj_bt_close_water";
global.__objectNames[600] = "obj_water_level_control";
global.__objectNames[601] = "obj_lava_water";
global.__objectNames[602] = "obj_lava_water_drybones";
global.__objectNames[603] = "obj_ventana_water";
global.__objectNames[604] = "obj_button_speed_water";
global.__objectNames[605] = "obj_ventana";
global.__objectNames[606] = "obj_window_button";
global.__objectNames[607] = "obj_button_wings";
global.__objectNames[608] = "obj_modo_sonidos_control";
global.__objectNames[609] = "obj_change_world";
global.__objectNames[610] = "obj_editormanager";
global.__objectNames[611] = "obj_mario_editor";
global.__objectNames[612] = "obj_parent_layout";
global.__objectNames[613] = "obj_parent_save";
global.__objectNames[614] = "obj_parent_resource";
global.__objectNames[615] = "obj_parent_sounds";
global.__objectNames[616] = "obj_creation_preview";
global.__objectNames[617] = "obj_resource_empty";
global.__objectNames[618] = "obj_cursor";
global.__objectNames[619] = "obj_grid";
global.__objectNames[620] = "obj_player_trail";
global.__objectNames[621] = "obj_effect_touch";
global.__objectNames[622] = "obj_arrow_lock";
global.__objectNames[623] = "obj_button_trail";
global.__objectNames[624] = "obj_call_mario";
global.__objectNames[625] = "obj_silbido";
global.__objectNames[626] = "obj_shadow";
global.__objectNames[627] = "obj_uni_parent_sizabledraw";
global.__objectNames[628] = "obj_editor_title";
global.__objectNames[629] = "obj_parent_sizabledraw";
global.__objectNames[630] = "obj_change_view";


// create another array that has the correct entries
var len = array_length_1d(global.__objectDepths);
global.__objectID2Depth = [];
for( var i=0; i<len; ++i ) {
	var objID = asset_get_index( global.__objectNames[i] );
	if (objID >= 0) {
		global.__objectID2Depth[ objID ] = global.__objectDepths[i];
	} // end if
} // end for