var mundos, _wrapper, _list, _map, _root_list2_m1, _map2_m1, _list2, _root_list3_m1, j, _map2, _map3, _list5, _root_list6_m1, l, _map5, _map6_m1, _list3, _root_list_m1, k, _map_m1, _list4, _root_list4_m1, _map4, _map4_m1, _list6, _root_list5_m1, _map6, _map5_m1, _list7, _root_list7_m1, _map7, _map7_m1, _list8, _root_list8_m1, _map8, _map8_m1, _list9, _root_list9_m1, _map9, _map9_m1, _wrapper_m1, mundo, _string;
mundos = LoadJSONFromFile((global.directorio_temporal + "nivel_temporal.swet"))
if (global.world_pipe == 0)
    _wrapper = ds_map_find_value(mundos, "SUB1")
else
    _wrapper = ds_map_find_value(mundos, "MAIN")
_list = ds_map_find_value(_wrapper, "AJUSTES")
_map = ds_list_find_value(_list, 0)
_root_list2_m1 = ds_list_create()
_map2_m1 = ds_map_create()
ds_list_add(_root_list2_m1, _map2_m1)
ds_list_mark_as_map(_root_list2_m1, (ds_list_size(_root_list2_m1) - 1))
ds_map_add(_map2_m1, "apariencia", ds_map_find_value(_map, "apariencia"))
ds_map_add(_map2_m1, "entorno", ds_map_find_value(_map, "entorno"))
ds_map_add(_map2_m1, "cronometro", ds_map_find_value(_map, "cronometro"))
ds_map_add(_map2_m1, "autoavance", ds_map_find_value(_map, "autoavance"))
ds_map_add(_map2_m1, "modo_noche", ds_map_find_value(_map, "modo_noche"))
ds_map_add(_map2_m1, "ground2", ds_map_find_value(_map, "ground2"))
ds_map_add(_map2_m1, "ground3_x", ds_map_find_value(_map, "ground3_x"))
ds_map_add(_map2_m1, "ground3_y", ds_map_find_value(_map, "ground3_y"))
ds_map_add(_map2_m1, "size", ds_map_find_value(_map, "size"))
ds_map_add(_map2_m1, "water_level", ds_map_find_value(_map, "water_level"))
ds_map_add(_map2_m1, "water_level_limit", ds_map_find_value(_map, "water_level_limit"))
ds_map_add(_map2_m1, "water_level_speed", ds_map_find_value(_map, "water_level_speed"))
ds_map_add(_map2_m1, "condiciones", ds_map_find_value(_map, "condiciones"))
ds_map_add(_map2_m1, "condiciones_type", ds_map_find_value(_map, "condiciones_type"))
ds_map_add(_map2_m1, "condiciones_object", ds_map_find_value(_map, "condiciones_object"))
ds_map_add(_map2_m1, "condiciones_count", ds_map_find_value(_map, "condiciones_count"))
_list2 = ds_map_find_value(_wrapper, "SUELO")
_root_list3_m1 = ds_list_create()
for (j = 0; j < ds_list_size(_list2); j++)
{
    _map2 = ds_list_find_value(_list2, j)
    _map3 = ds_map_create()
    ds_list_add(_root_list3_m1, _map3_m1)
    ds_list_mark_as_map(_root_list3_m1, (ds_list_size(_root_list3_m1) - 1))
    ds_map_add(_map3_m1, "x_pos", ds_map_find_value(_map2, "x_pos"))
    ds_map_add(_map3_m1, "y_pos", ds_map_find_value(_map2, "y_pos"))
    ds_map_add(_map3_m1, "index", ds_map_find_value(_map2, "index"))
}
_list5 = ds_map_find_value(_wrapper, "DECORACION")
_root_list6_m1 = ds_list_create()
for (l = 0; l < ds_list_size(_list5); l++)
{
    _map5 = ds_list_find_value(_list5, l)
    _map6_m1 = ds_map_create()
    ds_list_add(_root_list6_m1, _map6_m1)
    ds_list_mark_as_map(_root_list6_m1, (ds_list_size(_root_list6_m1) - 1))
    ds_map_add(_map6_m1, "object", ds_map_find_value(_map5, "object"))
    ds_map_add(_map6_m1, "x_pos", ds_map_find_value(_map5, "x_pos"))
    ds_map_add(_map6_m1, "y_pos", ds_map_find_value(_map5, "y_pos"))
    ds_map_add(_map6_m1, "sprite", ds_map_find_value(_map5, "sprite"))
    ds_map_add(_map6_m1, "index", ds_map_find_value(_map5, "index"))
}
_list3 = ds_map_find_value(_wrapper, "NIVEL")
_root_list_m1 = ds_list_create()
for (k = 0; k < ds_list_size(_list3); k++)
{
    _map3 = ds_list_find_value(_list3, k)
    _map_m1 = ds_map_create()
    ds_list_add(_root_list_m1, _map_m1)
    ds_list_mark_as_map(_root_list_m1, (ds_list_size(_root_list_m1) - 1))
    ds_map_add(_map_m1, "object", ds_map_find_value(_map3, "object"))
    ds_map_add(_map_m1, "x_pos", ds_map_find_value(_map3, "x_pos"))
    ds_map_add(_map_m1, "y_pos", ds_map_find_value(_map3, "y_pos"))
    ds_map_add(_map_m1, "sprout", ds_map_find_value(_map3, "sprout"))
    ds_map_add(_map_m1, "progresivo", ds_map_find_value(_map3, "progresivo"))
    ds_map_add(_map_m1, "wings", ds_map_find_value(_map3, "wings"))
    ds_map_add(_map_m1, "rotacion", ds_map_find_value(_map3, "rotacion"))
    ds_map_add(_map_m1, "direct_t", ds_map_find_value(_map3, "direct_t"))
    ds_map_add(_map_m1, "paracaidas", ds_map_find_value(_map3, "paracaidas"))
    ds_map_add(_map_m1, "key", ds_map_find_value(_map3, "key"))
    ds_map_add(_map_m1, "inup", ds_map_find_value(_map3, "inup"))
    ds_map_add(_map_m1, "modo_water", ds_map_find_value(_map3, "modo_water"))
    ds_map_add(_map_m1, "s_scaley", ds_map_find_value(_map3, "s_scaley"))
}
_list4 = ds_map_find_value(_wrapper, "TUBERIAS")
_root_list4_m1 = ds_list_create()
for (l = 0; l < ds_list_size(_list4); l++)
{
    _map4 = ds_list_find_value(_list4, l)
    _map4_m1 = ds_map_create()
    ds_list_add(_root_list4_m1, _map4_m1)
    ds_list_mark_as_map(_root_list4_m1, (ds_list_size(_root_list4_m1) - 1))
    ds_map_add(_map4_m1, "x_pos", ds_map_find_value(_map4, "x_pos"))
    ds_map_add(_map4_m1, "y_pos", ds_map_find_value(_map4, "y_pos"))
    ds_map_add(_map4_m1, "size", ds_map_find_value(_map4, "size"))
    ds_map_add(_map4_m1, "rotacion", ds_map_find_value(_map4, "rotacion"))
    ds_map_add(_map4_m1, "direct_t", ds_map_find_value(_map4, "direct_t"))
    ds_map_add(_map4_m1, "sprite", ds_map_find_value(_map4, "sprite"))
    ds_map_add(_map4_m1, "scalex", ds_map_find_value(_map4, "scalex"))
    ds_map_add(_map4_m1, "color", ds_map_find_value(_map4, "color"))
    ds_map_add(_map4_m1, "mask", ds_map_find_value(_map4, "mask"))
}
_list6 = ds_map_find_value(_wrapper, "CANNON")
_root_list5_m1 = ds_list_create()
for (l = 0; l < ds_list_size(_list6); l++)
{
    _map6 = ds_list_find_value(_list6, l)
    _map5_m1 = ds_map_create()
    ds_list_add(_root_list5_m1, _map5_m1)
    ds_list_mark_as_map(_root_list5_m1, (ds_list_size(_root_list5_m1) - 1))
    ds_map_add(_map5_m1, "object", ds_map_find_value(_map6, "object"))
    ds_map_add(_map5_m1, "x_pos", ds_map_find_value(_map6, "x_pos"))
    ds_map_add(_map5_m1, "y_pos", ds_map_find_value(_map6, "y_pos"))
    ds_map_add(_map5_m1, "direct", ds_map_find_value(_map6, "direct"))
    ds_map_add(_map5_m1, "down", ds_map_find_value(_map6, "down"))
    ds_map_add(_map5_m1, "up", ds_map_find_value(_map6, "up"))
    ds_map_add(_map5_m1_map5_m1, "left", ds_map_find_value(_map6, "left"))
    ds_map_add(_map5_m1, "right", ds_map_find_value(_map6, "right"))
}
_list7 = ds_map_find_value(_wrapper, "PLATAFORMAS")
_root_list7_m1 = ds_list_create()
for (l = 0; l < ds_list_size(_list7); l++)
{
    _map7 = ds_list_find_value(_list7, l)
    _map7_m1 = ds_map_create()
    ds_list_add(_root_list7_m1, _map7_m1)
    ds_list_mark_as_map(_root_list7_m1, (ds_list_size(_root_list7_m1) - 1))
    ds_map_add(_map7_m1, "object", ds_map_find_value(_map7, "object"))
    ds_map_add(_map7_m1, "x_pos", ds_map_find_value(_map7, "x_pos"))
    ds_map_add(_map7_m1, "y_pos", ds_map_find_value(_map7, "y_pos"))
    ds_map_add(_map7_m1, "sprite", ds_map_find_value(_map7, "sprite"))
    ds_map_add(_map7_m1, "color", ds_map_find_value(_map7, "color"))
    ds_map_add(_map7_m1, "depth", ds_map_find_value(_map7, "depth"))
    ds_map_add(_map7_m1, "width", ds_map_find_value(_map7, "width"))
    ds_map_add(_map7_m1, "height", ds_map_find_value(_map7, "height"))
    ds_map_add(_map7_m1, "direct_t", ds_map_find_value(_map7, "direct_t"))
    ds_map_add(_map7_m1, "wings", ds_map_find_value(_map7, "wings"))
}
_list8 = ds_map_find_value(_wrapper, "PUERTAS")
_root_list8_m1 = ds_list_create()
for (l = 0; l < ds_list_size(_list8); l++)
{
    _map8 = ds_list_find_value(_list8, l)
    _map8_m1 = ds_map_create()
    ds_list_add(_root_list8_m1, _map8_m1)
    ds_list_mark_as_map(_root_list8_m1, (ds_list_size(_root_list8_m1) - 1))
    ds_map_add(_map8_m1, "object", ds_map_find_value(_map8, "object"))
    ds_map_add(_map8_m1, "x_pos", ds_map_find_value(_map8, "x_pos"))
    ds_map_add(_map8_m1, "y_pos", ds_map_find_value(_map8, "y_pos"))
    ds_map_add(_map8_m1, "door_x", ds_map_find_value(_map8, "door_x"))
    ds_map_add(_map8_m1, "door_y", ds_map_find_value(_map8, "door_y"))
}
_list9 = ds_map_find_value(_wrapper, "SONIDOS")
_root_list9_m1 = ds_list_create()
for (l = 0; l < ds_list_size(_list9); l++)
{
    _map9 = ds_list_find_value(_list9, l)
    _map9_m1 = ds_map_create()
    ds_list_add(_root_list9_m1, _map9_m1)
    ds_list_mark_as_map(_root_list9_m1, (ds_list_size(_root_list9_m1) - 1))
    ds_map_add(_map9_m1, "object", ds_map_find_value(_map9, "object"))
    ds_map_add(_map9_m1, "x_pos", ds_map_find_value(_map9, "x_pos"))
    ds_map_add(_map9_m1, "y_pos", ds_map_find_value(_map9, "y_pos"))
}
ds_map_destroy(_wrapper)
_wrapper_m1 = ds_map_create()
ds_map_add_list(_wrapper_m1, "AJUSTES", _root_list2_m1)
ds_map_add_list(_wrapper_m1, "SUELO", _root_list3_m1)
ds_map_add_list(_wrapper_m1, "DECORACION", _root_list6_m1)
ds_map_add_list(_wrapper_m1, "NIVEL", _root_list_m1)
ds_map_add_list(_wrapper_m1, "TUBERIAS", _root_list4_m1)
ds_map_add_list(_wrapper_m1, "CANNON", _root_list5_m1)
ds_map_add_list(_wrapper_m1, "PLATAFORMAS", _root_list7_m1)
ds_map_add_list(_wrapper_m1, "PUERTAS", _root_list8_m1)
ds_map_add_list(_wrapper_m1, "SONIDOS", _root_list9_m1)
event_user(2)
mundo = ds_map_create()
if (global.world_pipe == 0)
{
    ds_map_add_map(mundo, "MAIN", _wrapper)
    ds_map_add_map(mundo, "SUB1", _wrapper_m1)
}
else
{
    ds_map_add_map(mundo, "MAIN", _wrapper_m1)
    ds_map_add_map(mundo, "SUB1", _wrapper)
}
_string = json_encode(mundo)
SaveStringToFile((global.directorio_temporal + "nivel_temporal.swet"), _string)
ds_map_destroy(_wrapper_m1)
ds_map_destroy(_wrapper)
event_user(3)
if (global.world_pipe == 0)
    global.world_pipe = 1
else
    global.world_pipe = 0
instance_destroy()

